version: "3.7"

services:
  gatekeeper:
    container_name: gatekeeper
    build:
      context: ..
      dockerfile: build/Dockerfile
      args:
        LDFLAGS: ${LDFLAGS}
    ports:
      - "${PORT}:${PORT}"
      - "${PROMETHEUS_PORT}:${PROMETHEUS_PORT}" # prometheus
    restart: always
    depends_on:
      - prometheus
    networks:
      - monitoring

  prometheus:
    container_name: prometheus
    build:
      context: ..
      dockerfile: build/prometheus/Dockerfile
      network: host
    ports:
      - "9090:9090"
    restart: always
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge